"""Widen Generalc.name for longer AI-post category labels

Revision ID: 35b02177d2d0
Revises: 68aa2ca63555
Create Date: 2026-07-12 10:49:53.972539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35b02177d2d0'
down_revision = '68aa2ca63555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # (unrelated 'ix_ad_click_ad_id' / 'ix_ad_impression_ad_id' index drift
    # again omitted here — see the note in 68aa2ca63555, not this migration's
    # concern)
    with op.batch_alter_table('generalc', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generalc', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
