"""add view_count to shtick

Revision ID: 3fab98ab4d4e
Revises: aeef03c8368d
Create Date: 2026-06-22 16:45:50.213343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fab98ab4d4e'
down_revision = 'aeef03c8368d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shtick', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_count', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shtick', schema=None) as batch_op:
        batch_op.drop_column('view_count')

    # ### end Alembic commands ###
