"""Add Hock forum and content pipeline tables

Revision ID: 68aa2ca63555
Revises: 9f3d1c7a2e5b
Create Date: 2026-07-12 10:40:48.922204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68aa2ca63555'
down_revision = '9f3d1c7a2e5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hock_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.public_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('youtube_channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('added_by', sa.String(length=50), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('last_video_id', sa.String(length=32), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['user.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_table('hock_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('hock_post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hock_post_id'], ['hock_post.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['hock_comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.public_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hock_post_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hock_post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hock_post_id'], ['hock_post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hock_post_id', 'user_id', name='uq_hock_post_like')
    )
    op.create_table('scraped_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('shtick_id', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shtick_id'], ['shtick.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'url', name='uq_scraped_article_source_url')
    )
    op.create_table('youtube_video_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('shtick_id', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['youtube_channel.channel_id'], ),
    sa.ForeignKeyConstraint(['shtick_id'], ['shtick.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    op.create_table('hock_comment_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hock_comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hock_comment_id'], ['hock_comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hock_comment_id', 'user_id', name='uq_hock_comment_like')
    )
    # NOTE: autogenerate also detected 'ix_ad_click_ad_id' / 'ix_ad_impression_ad_id'
    # as "removed" indexes — pre-existing schema drift unrelated to this
    # migration (those indexes exist in the live DB but aren't declared with
    # index=True on the current Ad models). Deliberately left untouched here;
    # not this migration's concern.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hock_comment_like')
    op.drop_table('youtube_video_post')
    op.drop_table('scraped_article')
    op.drop_table('hock_post_like')
    op.drop_table('hock_comment')
    op.drop_table('youtube_channel')
    op.drop_table('hock_post')
    # ### end Alembic commands ###
