"""add moderation fields to comment, hock_comment, hock_post

Revision ID: 6b7a0cdedb6a
Revises: d69bc54ee9ed
Create Date: 2026-07-14 10:13:58.532797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7a0cdedb6a'
down_revision = 'd69bc54ee9ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_to_publish', sa.Boolean(), server_default='true', nullable=False))

    with op.batch_alter_table('hock_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_to_publish', sa.Boolean(), server_default='true', nullable=False))

    with op.batch_alter_table('hock_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_to_publish', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('approved_by', sa.String(length=50), nullable=True))
        batch_op.create_index('ix_hock_post_approved_pub_date', ['approved_to_publish', 'pub_date'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['approved_by'], ['public_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hock_post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_hock_post_approved_pub_date')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('approved_to_publish')

    with op.batch_alter_table('hock_comment', schema=None) as batch_op:
        batch_op.drop_column('approved_to_publish')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('approved_to_publish')

    # ### end Alembic commands ###
