"""add role last_login approved_by comment game_score shtick_categories

Revision ID: aeef03c8368d
Revises: 
Create Date: 2026-06-22 15:04:49.338508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeef03c8368d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shtick', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_by', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['approved_by'], ['public_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_column('is_boss')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_boss', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.drop_column('last_login')
        batch_op.drop_column('role')

    with op.batch_alter_table('shtick', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('approved_by')

    # ### end Alembic commands ###
