"""add tachlis tables

Revision ID: c12622cade6d
Revises: cbdd724ca633
Create Date: 2026-07-13 12:20:53.134184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12622cade6d'
down_revision = 'cbdd724ca633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tachlis_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('contact', sa.String(length=300), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('compensation', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.Column('approved_to_publish', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.String(length=50), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.public_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.public_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tachlis_post', schema=None) as batch_op:
        batch_op.create_index('ix_tachlis_post_approved_pub_date', ['approved_to_publish', 'pub_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tachlis_post_post_type'), ['post_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_tachlis_post_pub_date'), ['pub_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tachlis_post_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tachlis_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tachlis_post_user_id'))
        batch_op.drop_index(batch_op.f('ix_tachlis_post_pub_date'))
        batch_op.drop_index(batch_op.f('ix_tachlis_post_post_type'))
        batch_op.drop_index('ix_tachlis_post_approved_pub_date')

    op.drop_table('tachlis_post')
    # ### end Alembic commands ###
