"""add missing indexes on shtick, comment, like, hock tables

Revision ID: cbdd724ca633
Revises: 35b02177d2d0
Create Date: 2026-07-13 11:16:56.451525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbdd724ca633'
down_revision = '35b02177d2d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_shtick_id'), ['shtick_id'], unique=False)

    with op.batch_alter_table('hock_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hock_comment_hock_post_id'), ['hock_post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hock_comment_parent_comment_id'), ['parent_comment_id'], unique=False)

    with op.batch_alter_table('hock_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hock_post_pub_date'), ['pub_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_hock_post_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_like_shtick_id'), ['shtick_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_like_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('shtick', schema=None) as batch_op:
        batch_op.create_index('ix_shtick_approved_pub_date', ['approved_to_publish', 'pub_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_shtick_generalc_id'), ['generalc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shtick_pub_date'), ['pub_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_shtick_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shtick', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shtick_user_id'))
        batch_op.drop_index(batch_op.f('ix_shtick_pub_date'))
        batch_op.drop_index(batch_op.f('ix_shtick_generalc_id'))
        batch_op.drop_index('ix_shtick_approved_pub_date')

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_like_user_id'))
        batch_op.drop_index(batch_op.f('ix_like_shtick_id'))

    with op.batch_alter_table('hock_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hock_post_user_id'))
        batch_op.drop_index(batch_op.f('ix_hock_post_pub_date'))

    with op.batch_alter_table('hock_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hock_comment_parent_comment_id'))
        batch_op.drop_index(batch_op.f('ix_hock_comment_hock_post_id'))

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_shtick_id'))

    # ### end Alembic commands ###
